import * as fs from "fs";
import * as os from "os";
import * as path from "path";

/**
 * Local-only onboarding counters for the "extension as onboarding entry
 * point" flow (siropkin/budi#314).
 *
 * This file lives next to `cursor-sessions.json` under
 * `~/.local/share/budi/` so both the extension and `budi doctor` can read it
 * without any remote telemetry. Counts only — no prompts, no code, no
 * timestamps beyond coarse first/last markers. The file stays inside
 * ADR-0083 privacy limits (no file contents, no outside-of-repo paths)
 * because it only stores integer counters and ISO timestamps generated by
 * the extension itself.
 *
 * Format (v1):
 * ```json
 * {
 *   "version": 1,
 *   "welcome_view_impressions": 3,
 *   "open_terminal_clicks": 1,
 *   "handoffs_completed": 1,
 *   "first_impression_at": "2026-04-17T10:00:00.000Z",
 *   "last_impression_at":  "2026-04-17T10:05:00.000Z",
 *   "last_handoff_at":     "2026-04-17T10:05:30.000Z"
 * }
 * ```
 *
 * Missing fields default to 0 / null. `budi doctor` silently skips the
 * surface when the file does not exist.
 */

export const COUNTERS_VERSION = 1;

export const DEFAULT_COUNTERS_DIR = path.join(os.homedir(), ".local", "share", "budi");
export const DEFAULT_COUNTERS_FILE = path.join(DEFAULT_COUNTERS_DIR, "cursor-onboarding.json");

export interface OnboardingCounters {
  version: number;
  welcome_view_impressions: number;
  open_terminal_clicks: number;
  handoffs_completed: number;
  first_impression_at: string | null;
  last_impression_at: string | null;
  last_handoff_at: string | null;
}

export type CounterEvent = "welcome_view_impression" | "open_terminal_click" | "handoff_completed";

function emptyCounters(): OnboardingCounters {
  return {
    version: COUNTERS_VERSION,
    welcome_view_impressions: 0,
    open_terminal_clicks: 0,
    handoffs_completed: 0,
    first_impression_at: null,
    last_impression_at: null,
    last_handoff_at: null,
  };
}

function sanitize(value: unknown): OnboardingCounters {
  if (!value || typeof value !== "object") return emptyCounters();
  const raw = value as Partial<OnboardingCounters>;
  const pickInt = (n: unknown): number => {
    if (typeof n !== "number" || !Number.isFinite(n) || n < 0) return 0;
    return Math.floor(n);
  };
  const pickIso = (s: unknown): string | null => (typeof s === "string" ? s : null);
  return {
    version: COUNTERS_VERSION,
    welcome_view_impressions: pickInt(raw.welcome_view_impressions),
    open_terminal_clicks: pickInt(raw.open_terminal_clicks),
    handoffs_completed: pickInt(raw.handoffs_completed),
    first_impression_at: pickIso(raw.first_impression_at),
    last_impression_at: pickIso(raw.last_impression_at),
    last_handoff_at: pickIso(raw.last_handoff_at),
  };
}

/**
 * Read the counters file. Returns default zeros if the file does not
 * exist or is malformed — callers never need to special-case "first
 * run" themselves.
 */
export function readCounters(file: string = DEFAULT_COUNTERS_FILE): OnboardingCounters {
  try {
    const raw = fs.readFileSync(file, "utf-8");
    return sanitize(JSON.parse(raw));
  } catch {
    return emptyCounters();
  }
}

/**
 * Apply one of three counter events and persist the updated totals.
 *
 * Best-effort: disk errors are swallowed so we never crash the
 * extension over a local counter. Accepts an injected `now` to keep
 * tests deterministic.
 */
export function recordCounterEvent(
  event: CounterEvent,
  file: string = DEFAULT_COUNTERS_FILE,
  now: Date = new Date(),
): OnboardingCounters {
  const current = readCounters(file);
  const nowIso = now.toISOString();
  const next: OnboardingCounters = { ...current, version: COUNTERS_VERSION };

  if (event === "welcome_view_impression") {
    next.welcome_view_impressions = current.welcome_view_impressions + 1;
    next.last_impression_at = nowIso;
    if (!next.first_impression_at) next.first_impression_at = nowIso;
  } else if (event === "open_terminal_click") {
    next.open_terminal_clicks = current.open_terminal_clicks + 1;
  } else if (event === "handoff_completed") {
    next.handoffs_completed = current.handoffs_completed + 1;
    next.last_handoff_at = nowIso;
  }

  try {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, JSON.stringify(next, null, 2) + "\n");
  } catch {
    // best-effort — local counters must never crash the extension
  }
  return next;
}
